---
mailing_list_email: rails-starcraft@googlegroups.com
mailing_list_url: groups.google.com/group/rails-starcraft/
signup_form_url:  'https://spreadsheets.google.com/viewform?authkey=CP6UyZ0H&hl=en&formkey=dE9RUmpYV3ViSkE5dkVSd3UyX1RZRHc6MQ#gid=0'
